export const FETCH_TRANSACTIONS = 'FETCH TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD TRANSACTION';
export const ADD_USER = 'ADD USER';
export const UPDATE_USER_FUNDS = 'UPDATE USER FUNDS';
export const USER_PAY_FOR_TICKET = 'USER PAY FOR TICKET'